# Microsoft AI School - NumPy Library
* Date: 2024/12/27
* Python Version: 3.13.1
* Notes: NumPy Version: 2.2.1

# 1. NumPy
* Purpsoe: NumPy is a library designed for mathematical and scientific computations, such as algebra, matrix operations, and statistics.
* Feature: 
    * Provides more efficient way to represent and process data using ndarray, a multi-dimensional array object.
    * High execution speed.
    * Enables concise and efficient code.
* Installation: It is an external library so it needs to be installed before use.

In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.6 MB 11.6 MB/s eta 0:00:01
   -------------- ------------------------- 4.7/12.6 MB 11.6 MB/s eta 0:00:01
   ---------------------- ----------------- 7.1/12.6 MB 11.6 MB/s eta 0:00:01
   ----------------------------- ---------- 9.4/12.6 MB 11.6 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 11.6 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 11.4 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [3]:
numpy.__version__

'2.2.1'

# 2. NumPy Arrays
* NumPy provides robust support for creating and working with arrays of multiple dimensions.
    * Vector: 1-D
    * Matrix: 2-D
    * Tensor (3-D)
* Homogeneous Data: All elements in a NumPy array have the same data type, ensuring effcient memory usage and enabling optimized mathematical operations.

### A. Difference Between NumPy Arrays and Python Lists
* Storage
    * Python Lists: Store references (addresses) to the actual data, allowing elements of mixed data types.
    * NumPy Arrays: Store actual data within the array, ensuring all elements are of the same data type for optimized memory use.
* Performance
    * Python Lists: Slower for large-scale data processing, taking approximately twice as long to read and write compared to NumPy arrays.
    * NumPy Arrays: Faster due to contiguous memory storage and efficient low-level operations.
* Use Case:
    * Python Lists: Suitable for small datasets or when working with diverse data types.
    * NumPy Arrays: Ideal for large-scale numerical computations, matrix operations, and data-heavy tasks.
* Advantages of NumPy for Mathematical Operations
    * Highly efficient for bulk operations on arrays and matrices.
    * Provides a vast library of mathematical and statistical functions optimize for speed and accuracy.

# 3. Syntax

## A. Creating a NumPy array object
* Creatiing a NumPy Array from a Python list object
    * np.array({list_object})
* Creating a NumPy array by defining a range from start index to end index.
    * np.arrange(start, end, step)

In [4]:
import numpy as np

In [12]:
# Create a NumPy array from a list
num_list = [1 ,2, 3, 4]
int_arr = np.array(num_list)
print(type(num_list))
print(int_arr)
print(type(int_arr))

<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
# Create a NumPy array by specifing range
arr1 = np.arange(0, 10)
arr2 = np.arange(0, 10, 2)
arr3 = np.arange(5)

print(arr1)
print(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 1 2 3 4]


In [10]:
# Creating 2-dimensional array: matrix
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
# Creating a 3-dimensional array: tensor
arr_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]],
                   [[9, 10, 11, 12], [13, 14, 15, 16]],
                   [[17, 18, 19, 20], [21, 22, 23, 24]]])
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


*  Creating a NumPy array by specifying the range, in a start index: end index pair, and the number of elements to be generated in the array.
    * np.linspace(start, end, number of elements)

In [34]:
arr = np.linspace(1, 10, 10)
print(arr)
print(arr.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


##### NumPy Enforcing Homogeneity

In [14]:
# NumPy enforcing Homogeneity
list_data = [1, '2', 3]
arr = np.array(list_data)

print(arr)

['1' '2' '3']


In [15]:
arr2 = np.array([1, 2.5, 3])
print(arr2)

[1.  2.5 3. ]


## B. Checking the number of dimension of a NumPy array
* array.ndim to check the number of dimension of the array

In [24]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.ndim)

[1 2 3 4]
1


In [25]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


## C. Checking the size of the array
* array.shape

In [27]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(arr.shape)

[1 2 3 4]
(4,)


In [28]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


## D. Change the dimensions of a NumPy array
* array.reshape()

In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr.ndim)
print(arr.shape)
arr2 = arr.reshape(2, 5)
print(arr2.ndim)
print(arr2.shape)

1
(10,)
2
(2, 5)


In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr2 = arr.reshape(2, -1)       # when one of the arguments is set to -1, NumPy automatically computes it
print(arr2.ndim)
print(arr2.shape)

2
(2, 5)


## E. NumPy arithmetic operations
* Perform basic arithmetic operations - addition, subtraction, multiplication, and division - between two NumPy arrays of the same shape.

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## F. Vectorized Operation
* Element-wise operation on Python NumPy array objects

In [33]:
v = np.array([1, 2, 3])

print(v + 1)
print(v - 1)
print(v * 3)
print(v / 2)

[2 3 4]
[0 1 2]
[3 6 9]
[0.5 1.  1.5]


In [37]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
arr = np.array(data) * 2
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


## G. NumPy Array with Sepcial Values
* np.zeros()
* np.ones()
* np.eye()

#### np.zeros()

In [16]:
arr = np.zeros((10))
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
arr = np.zeros((2, 5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### np.ones()

In [18]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [20]:
arr = np.ones((2, 5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### np.eye()

In [21]:
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [23]:
arr = np.eye(5, dtype = int)
print(arr)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


# 4. Accessing NumPy Array Elements

### A. Indexing

In [44]:
a = np.array([[0, 1, 2], [3, 4, 5]])
# get 0
print(a[0, 0])
# get 1
print(a[0, 1])
# get 5
print(a[0, 2])

0
1
2


## B. Slicing

In [51]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
# get 0, 1, 2, 3
print(a[0])
# get 1, 5
print(a[ : , 1])
# get 5, 6, 7
print(a[1, 1:])
# get 0, 1, 4, 5
print(a[:, 0:2])

[0 1 2 3]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]
